sudo: required
language: generic
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty          
          env: VERSION=6
        - os: linux
          dist: trusty          
          env: VERSION=5
        # Use generic language for osx
        - os: osx
          osx_image: xcode8
          language: generic

install:
    - bash script/install-unix.sh
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-travis.sh | bash
script:
    - bash script/travis-build.sh
notifications:
    slack:
        secure: "J8S2WdWpg+uh+LYIfiY7LQ+vfhIKTNDnFz81zxZ0gfSzwmRvFJxxS7b6n3da6rRs8slvyXdSfaGoL38uESQEQmuTN1eONEXvoTGnIMUbVjZ8FehXUd0HsmAi+qQWqg4s0vmUHm+ZzhjI8Dt/Fdf/EcUkFDovrn4VPpgUC/8yzz85CUM/ONzrdrVxOuBlZdvDE9yYcQ9aZTwzJ9OkzNbHHYfsZnGQwRFSp2gbPA4gsHT7bx8JE19qatqVy4TAqlNNRtN3q8rRlLWbaupFO+JRWT3RV3NB9BFwjMB+9cWMBXH6Qu0hnJQGsP8p/gK4dkbOrTQMLLYNihcTXTyRxRBAxvtA9cwTR4+zBqIu+ERrJ/E0Hh0ZpClW+FvEtcTsZ14PV/zzsuvpyEfWwwMMUNR5uPDe29lKCyETE+rOY1crfrCCeXMHgwS0LsZbwCehzr+n8MMPmv8JZRmLUJ9eF0s8kPgSK+NrZv7vnSOF5/cDObJEuiGDAtVndcyMYAHkKbD84JVIn4ZfaB8BS7pRsl9F8MqRqL0CQC2Gpl+V+BGx/6u/ErvuM0OBTC/2nwtK4PdHxyXficgZWoJQLUSqiCaqPICVYDZK6U+/uVW9FxkHLpvsVZlxlbHjjcxoexOj5DOu6R9bmLFYANGfllnT2u0tRbq5C5eiehi2+W04hbLctLM="